# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: monk_urgeüöπ

on:
  workflow_dispatch:
  schedule:
    - cron: '28 9 18-26 5 *'
  repository_dispatch:
    types: adolf_urge
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # ‰ΩøÁî® GitHub ÂÆòÊñπÁöÑÁºìÂ≠ò Action„ÄÇ
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ‰ΩøÁî® package-lock.json ÁöÑ Hash ‰Ωú‰∏∫ÁºìÂ≠òÁöÑ key„ÄÇ‰πüÂèØ‰ª•‰ΩøÁî® package.json ‰ª£Êõø
      - name: npm install
        run: |
          npm install
      - name: 'ËøêË°å monk_urgeüöπ'
        run: |
          node monk_urge.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}JD_US
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
